# fly.toml app configuration file generated for fosdem25-datastar on 2025-02-01T14:46:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fosdem25-datastar'
primary_region = 'ams'

[build]

[env]
  PORT = '8787'

[processes]
  app = 'run -A ./main.ts'

[http_service]
  internal_port = 8787
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
